import type { Metadata } from "next";
import localFont from "next/font/local";
import { Corinthia } from "next/font/google";

import Providers from "@/components/Providers";
import Footer from "@/components/base/footer";
import Header from "@/components/base/header";
import RightStickyBar from "@/components/base/RightStickyBar";
import PageIntroWrapper from "@/components/PageIntroWrapper";
import "./globals.css";

const corinthia = Corinthia({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-corinthia",
  display: "swap",
});

const helvetica = localFont({
  src: [
    {
      path: "../fonts/helvetica_neue_ce_55_roman-webfont.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/helvetica_neue_ce_55_roman-webfont.woff",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-helv",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en" 
      className={`${helvetica.variable} ${corinthia.variable}`}
      suppressHydrationWarning
    >
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function(){
                if ('scrollRestoration' in history) history.scrollRestoration = 'manual';
                var scrollTop = function(){ window.scrollTo(0,0); document.documentElement.scrollTop=0; document.body.scrollTop=0; };
                scrollTop();
                if (document.readyState === 'loading') {
                  document.addEventListener('DOMContentLoaded', scrollTop);
                  window.addEventListener('load', scrollTop);
                }
                window.addEventListener('pageshow', function(e){ if(e.persisted) scrollTop(); });
              })();
            `,
          }}
        />
      </head>
      <body className="text-theme  transition-colors duration-200 scroll-lock">
        <Providers>
          <Header />
          <PageIntroWrapper>
            {children}
            <Footer />
          </PageIntroWrapper>
          <RightStickyBar />
        </Providers>
      </body>
    </html>
  );
}
