import type { Metadata } from "next";
import localFont from "next/font/local";
import { Corinthia } from "next/font/google";

import Providers from "@/components/Providers";
import Footer from "@/components/base/footer";

import "./globals.css";

const corinthia = Corinthia({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-corinthia",
  display: "swap",
});

const helvetica = localFont({
  src: [
    {
      path: "../fonts/helvetica_neue_ce_55_roman-webfont.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/helvetica_neue_ce_55_roman-webfont.woff",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-helv",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${helvetica.variable} ${corinthia.variable}`}
      suppressHydrationWarning
    >
      <body className="bg-white text-black dark:bg-[#0b0b0b] dark:text-white">
        <Providers>
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
